### ISSUE TITLE
Python 3.5 Compatibility?

### ISSUE THREAD

**Issue by alexk403** [kronenthaler/mod-pbxproj#101]
Tried using this package on python 3.5 and it failed trying to import, saying 

`ImportError: cannot import name 'XcodeProject'`

**Comment by kronenthaler** [comment]
What branch are you tryinb to use?

**Comment by alexk403** [comment]
Installing through pip

**Comment by kronenthaler** [comment]
Sorry for the late reply, i checked the package is not compatibly with python 3, a.t.m. only python 2.x. 
Currently i'm heavily refactoring the project, seems unlikely that I will provide support for python 3 whilst the default installation on most platforms (linux and osx) is python 2.x.
After the refactor phase, i will start introducing support for python 3.x.

**Comment by rublevma** [comment]
Still not compatible with 3.5?

**Comment by kronenthaler** [comment]
python 3 support added on pbxproj 2.2.0
