### ISSUE TITLE
.bundle file is in incorrect build phase

### ISSUE THREAD

**Issue by fengye** [kronenthaler/mod-pbxproj#12]
Using add_file() to add .bundle to pbxproj will render the bundle not included in build phase.

See mod_pbxproj.py, line 192

if os.path.isdir(self.get('path')) and ext != '.framework':

it only take cares of .framework. I changed it to 

if os.path.isdir(self.get('path')) and ext != '.framework' and ext != '.bundle':

Problem solved.

**Comment by JohnBueno** [comment]
Was this ever corrected?  I am running into the same problem however I think I am in a different version because I don't see the os.path.isdir(self.get('path')) and ext != '.framework': line

**Comment by kronenthaler** [comment]
The fix was included while ago. Most likely you need to update your version.

**Comment by JohnBueno** [comment]
Hey thanks for getting back to me so quickly!  I updated to what you currently have and I am getting the following error when I try to run it.

File "Assets/Editor/post_process.py", line 4, in <module>
    from mod_pbxproj import XcodeProject
  File "/Users/bueno/Developer/sm/MightyIO-Unity-iOS-Binding/MightyIO-UnityDemo/Assets/Editor/mod_pbxproj.py", line 131
    return PBXDict(o)

Apologies this info might not be super helpful I am pretty new to Python
