### ISSUE TITLE
'PBXGenericObject' object has no attribute 'get_or_create_build_phase'

### ISSUE THREAD

**Issue by yodutouf** [kronenthaler/mod-pbxproj#122]
I try to add a framework to my xcodeproj.

I install the library using pip.

I test with the client or a python file. 

**I meet the same error: 'PBXGenericObject' object has no attribute 'get_or_create_build_phase'.**

How to solve this problem ?

## Command line

My command line for the client is 

`python -m pbxproj file --weak MyProj.xcodeproj libraries/MyFramework.framework`

## Using file

My code to update my xcodeproj is

```
from pbxproj import XcodeProject
from pbxproj.pbxextensions.ProjectFiles import FileOptions

project = XcodeProject.load('MyPoj.xcodeproj/project.pbxproj')

frameworks = project.get_or_create_group('Frameworks')
file_options = FileOptions(weak=True)
project.add_file('libraries/MyFramework.framework', parent=frameworks, force=False, file_options=file_options)

project.save()
```

**Comment by kronenthaler** [comment]
Thanks for your report. I will check it out, however, it seems that your project may have a section looking like this <XX>BuildPhase, that i haven't seen so far. It would be great if you could try a couple of things for me:

1. Create a "empty" project, or single view application, and run the scripts above. You should not have any errors here, if so, please copy the project.pbxproj file (insided of the .xcodeproj folder) into this thread for further investigation.
2. On your own project, open the project.pbxproj file, and search for `BuildPhase`, and take note off all different sections you find with that suffix. And copy that list into this thread so i could see if there is a section that i haven't seen before and be able to add it. I might need more details after this, but let's see how it goes.

**Comment by yodutouf** [comment]
I confirm it's working with an empty project. 

Sections:
PBXFrameworksBuildPhase
PBXHeadersBuildPhase
PBXResourcesBuildPhase
PBXShellScriptBuildPhase
PBXSourcesBuildPhase

I test with an other tool [xcodeproj](https://github.com/CocoaPods/Xcodeproj). It's add correctly the framework to my project

**Comment by kronenthaler** [comment]
Thanks i will investigate with this information.

**Comment by kronenthaler** [comment]
I dug a bit with the information, it seems that you have a type of target i haven't seen before. It would be great if you could share the xcode project file (project.pbxproj) with me, or at least, the sections with suffix Target.
