### ISSUE TITLE
how to add " .h"

### ISSUE THREAD

**Issue by shanghaiMichael** [kronenthaler/mod-pbxproj#132]
I want to add " .h" file through 'project.add_file('test.h')' ,  but raise a error"TypeError: hasattr(): attribute name must be string"

**Comment by kronenthaler** [comment]
Thanks for your report. Can you provide this information:
- Full stack trace of the error
- Versions you are using for: Xcode, iOS, pbxproj
- Where did you install pbxproj from: github clone or via pip.
