### ISSUE TITLE
Unity Xcode project can't create group

### ISSUE THREAD

**Issue by shanghaiMichael** [kronenthaler/mod-pbxproj#134]
[test-unity.zip](https://github.com/kronenthaler/mod-pbxproj/files/820634/test-unity.zip)

I want to add group in a Unity Xcode project , but it was bad .   Please find the Demo file attached.

**Comment by kronenthaler** [comment]
Thanks for your report. I will investigate further with this information.
Note to self: mainGroup is not the traditional default group.

**Comment by kronenthaler** [comment]
Fix on PR #135

**Comment by shanghaiMichael** [comment]
It's good for unity project .  But , it's bad for common project. #136

**Comment by shanghaiMichael** [comment]
I'm wrong

**Comment by shanghaiMichael** [comment]
thanks
