### ISSUE TITLE
bundle format unrecognized, invalid, or unsuitable

### ISSUE THREAD

**Issue by chenxi141017** [kronenthaler/mod-pbxproj#140]
I try to use this moudle to package My XcodeProject , I use the xcodebuild command to build it.

I used to use the 1.0.0 , it works well , but today I updated the moudle , the error code like this :   
 **```
Signing Identity:     "iPhone Developer: ruiqi shi (5UYM39ZA5R)"

    /usr/bin/codesign --force --sign 0B6CCF1493AF0B415323309622B1AB1EE1456A8D --preserve-metadata=identifier,entitlements --timestamp=none 

/Users/chenxi/autopack_lzws/ios/build/blank.proj_01GameCHINA/project/build/Release-iphoneos/TheThreeKingdoms.app/Frameworks/MobileCoreServices.framework
/Users/chenxi/autopack_lzws/ios/build/blank.proj_01GameCHINA/project/build/Release-iphoneos/TheThreeKingdoms.app/Frameworks/MobileCoreServices.framework: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1
```**

I add the system Framework like this ：

```
framework = 'System/Library/Frameworks/' + framework
			file_options = FileOptions(weak=True)
			parent = XcodeProject.get_or_create_group("Frameworks")
			XcodeProject.add_file(framework,parent=parent,tree='SDKROOT',force=False,file_options=file_options)

```

**Comment by liszto** [comment]
in your file options you do something similar to me in another issue. I don't say it will solve your problem but it would be better to do this : 
`
file_options = FileOptions(weak=bool(int(subListElem2)), embed_framework=False, code_sign_on_copy=False)
`

**Comment by kronenthaler** [comment]
It seems the same issue as @liszto mention. There is a PR open already for it #141

**Comment by chenxi141017** [comment]
is there anything i was wrong?

**Comment by kronenthaler** [comment]
@chenxi141017 actually you are forcing them to be added as "optional", by setting the weak=True you are adding all frameworks as optional instead of required.
The .a files are not affected by the weak flag at all, they are always compiled into your application.
Please close the ticket if after changing weak=False, it fixes your problem

**Comment by chenxi141017** [comment]
@kronenthaler  thank you very much ! It solved my problem!
