### ISSUE TITLE
Help with create groups

### ISSUE THREAD

**Issue by Naibeck** [kronenthaler/mod-pbxproj#146]
Hi, I was checking https://github.com/kronenthaler/mod-pbxproj/wiki/Groups-and-Folders#create-or-get-a-group and I want to create a recursive group using add_folder, the script seems to run fine since no exception is displayed but I can't see the group.

```
project = XcodeProject.load(main_project_build)
group = project.get_or_create_group('group') 
project.add_folder('path/to/folder', parent=group)
project.save()
```

The first group is created but the second is not, is this the correct way to create a group from an existing folder? 

Edited:
Now that I run the whole folder path is displaying this exception:
```
ValueError: Unknown file extension: .pch. Please add the extension and Xcode type to ProjectFiles._FILE_TYPES
```

**Comment by kronenthaler** [comment]
I have added the .pch extension to the list. Bear in mind that you will have to add a flag afterwards with: 

```
project.set_flags('GCC_PREFIX_HEADER', 'path/to/file.pch')
```
