### ISSUE TITLE
Help, open project Xcode crashed!

### ISSUE THREAD

**Issue by shanghaiMichael** [kronenthaler/mod-pbxproj#148]
[test.zip](https://github.com/kronenthaler/mod-pbxproj/files/1017644/test.zip)

The origin project is good in the path test->aaa->bbb->ROGame.xcodeproj.
The target project is crash in the path test->aaa->bbb->ROGame-iapps.xcodeproj.

Help me ,  please check out the attachment , thanks.

**Comment by shanghaiMichael** [comment]
I find the 'projectReferences' is wrong.

**Comment by kronenthaler** [comment]
a similar issue has been fixed in 2.0.8, please check what version are you using and upgrade if necessary.

**Comment by shanghaiMichael** [comment]
I'm using the latest version 2.0.9

**Comment by shanghaiMichael** [comment]
fixed
