### ISSUE TITLE
Error by adding a folder

### ISSUE THREAD

**Issue by Naibeck** [kronenthaler/mod-pbxproj#149]
ValueError: Unknown file extension: .def. Please add the extension and Xcode type to ProjectFiles._FILE_TYPES

**Comment by kronenthaler** [comment]
Thanks for your report. the .def file, what kind of content does it have?

**Comment by Naibeck** [comment]
https://msdn.microsoft.com/en-us/library/28d6s79h(VS.80).aspx don't know if this will help you
