### ISSUE TITLE
Error adding file with extension .xcconfig

### ISSUE THREAD

**Issue by Naibeck** [kronenthaler/mod-pbxproj#150]
ValueError: Unknown file extension: .xcconfig. Please add the extension and Xcode type to ProjectFiles._FILE_TYPES

**Comment by KarthikSankar29** [comment]
Just add 
`u'.xcconfig': (u'sourcecode.xcconfig', u'PBXSourcesBuildPhase')`
in _FILE_TYPES - class (ProjectFiles) file (ProjectFiles.py) found in '_pbxproj/pbxextensions/_'
Hope this helps.
