### ISSUE TITLE
Error adding files with no extension

### ISSUE THREAD

**Issue by Naibeck** [kronenthaler/mod-pbxproj#151]
ValueError: Unknown file extension: . Please add the extension and Xcode type to ProjectFiles._FILE_TYPES

**Comment by kronenthaler** [comment]
Thanks for you report. What kind of files are you trying to add without extension? what kind of content do they have?

**Comment by Naibeck** [comment]
Binary files, so basically when you try to merge unity with a xcodeproject it will use those binaries as a reference to load scenes (in this case). I could add the files by ignoring if the format exist

**Comment by kronenthaler** [comment]
I added the extensions in 2.0.10. However, you can choose to ignore the unknown types when adding a file by setting in the `FileOptions(ignore_unknown_type=True)`
