### ISSUE TITLE
How can I get a file's path

### ISSUE THREAD

**Issue by shanghaiMichael** [kronenthaler/mod-pbxproj#153]
I want get the 'AppDelegate.m' file's path (For example , the path is  './aaa/bbb/AppDelegate.m'). Is there anyway to do this?

**Comment by kronenthaler** [comment]
You can use:

```
ref = project.get_files_by_name("AppDelegate.m")
print ref.path
```
This will give you the path of the file. However, it might simply return you the name of the file. This is because depending how the file is added, you will need to iterate over the group structure and reconstruct the path.

Hope it helps
