### ISSUE TITLE
Git clone installation instructions not quite right; here's a fix

### ISSUE THREAD

**Issue by emaloney** [kronenthaler/mod-pbxproj#154]
Hello,

There is apparently no way to edit the wiki or submit a pull request to it, so I'll have to open a ticket.

Anyway, I tried [the setup.py installation instructions](https://github.com/kronenthaler/mod-pbxproj/wiki/Installation#using-setuppy) and they didn't work as written:

```bash
git clone https://github.com/kronenthaler/pbxproj.git
sudo python setup.py install
```

Instead, the instructions _will_ work with a slight modifications:

```bash
git clone https://github.com/kronenthaler/mod-pbxproj.git
cd mod-pbxproj
sudo python setup.py install
```

Hope this helps,
E.

**Comment by kronenthaler** [comment]
Thanks, fixed already
