### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'isa'

### ISSUE THREAD

**Issue by markshep** [kronenthaler/mod-pbxproj#155]
I'm using mod-pbxproj to manipulate an Xcode project file generated by Unity.  In the script it removes a file from the project then adds some others, but it's raising the exception when it tries to add the first of those additional files.  If the deletion is skipped then it works fine.  It's quite a complicated project file, but I've reduced it down to a smaller test case and worked out that the presence of a file assigned to the "Unity-iPhone Tests" target triggers this problem - if that's removed from the project file then the script works.

I've attached a tarball containing two example project files (one exhibiting this behaviour and one that doesn't) and a test script demonstrating the issue:

[bug.tar.gz](https://github.com/kronenthaler/mod-pbxproj/files/1072148/bug.tar.gz)

**Comment by kronenthaler** [comment]
Thanks for your report, i will take a look at it.

**Comment by kronenthaler** [comment]
Hello, i'm testing your report and i can't reproduce the error with your script.
I have installed the latest version 2.0.9. 

You can check the version you have installed by running this directly on the python terminal

```
import pbxproj
pbxproj.__version__
```

Keep in mind you can still use the `mod_pbxproj` module in your script as it acts like a proxy and installs `pbxproj` if it's not present.

**Comment by markshep** [comment]
I'm still getting the problem even with the latest 2.1.0 from master.  I'm running with MacPorts' python 2.7.13 on macOS Sierra 10.12.5.  I've attached an updated version of bug.tar.gz which now has a Makefile that uses virtualenv to create a Python instance and install the latest pbxproj release into it for testing.  This is the output I'm getting:

```
$ make
virtualenv venv
New python executable in /Users/mark/code/p1g/bug/venv/bin/python
Installing setuptools, pip, wheel...done.
venv/bin/pip install pbxproj
Collecting pbxproj
Collecting openstep-parser (from pbxproj)
Collecting docopt (from pbxproj)
Installing collected packages: openstep-parser, docopt, pbxproj
Successfully installed docopt-0.6.2 openstep-parser-1.2.2 pbxproj-2.1.0
[bug.tar.gz](https://github.com/kronenthaler/mod-pbxproj/files/1125529/bug.tar.gz)
venv/bin/python --version
Python 2.7.13
venv/bin/python test.py
Testing 'good.pbxproj'...
PASS

Testing 'bad.pbxproj'...
FAIL - got exception:
  Traceback (most recent call last):
    File "test.py", line 14, in test
      project.add_file('whatever.mm')
    File "/Users/mark/code/p1g/bug/venv/lib/python2.7/site-packages/pbxproj/pbxextensions/ProjectFiles.py", line 132, in add_file
      results.extend(self._create_build_files(file_ref, target_name, expected_build_phase, file_options))
    File "/Users/mark/code/p1g/bug/venv/lib/python2.7/site-packages/pbxproj/pbxextensions/ProjectFiles.py", line 403, in _create_build_files
      build_phases = target.get_or_create_build_phase(expected_build_phase)
    File "/Users/mark/code/p1g/bug/venv/lib/python2.7/site-packages/pbxproj/pbxsections/PBXGenericTarget.py", line 16, in get_or_create_build_phase
      current_build_phase = target_build_phase.isa
  AttributeError: 'NoneType' object has no attribute 'isa'

```

**Comment by markshep** [comment]
Upload failed - here it is now: [bug2.tar.gz](https://github.com/kronenthaler/mod-pbxproj/files/1125532/bug2.tar.gz)

**Comment by markshep** [comment]
I just tried it on another machine running the same version of macOS, but without MacPorts installed meaning that it was running the stock Apple python 2.7.10.  I had to run ```sudo easy_install pip```, and ```sudo pip install virtualenv``` before running ```make``` in order to get the test to run.

One it was running it also raised the same AttributeError exception, so I don't know why you're not seeing the issue :-(.

**Comment by kronenthaler** [comment]
I will reopen and check again

**Comment by kronenthaler** [comment]
fixed
