### ISSUE TITLE
Support linking a library output from a child .xcodeproj

### ISSUE THREAD

**Issue by markshep** [kronenthaler/mod-pbxproj#156]
I'd like to add a child .xcodeproj to my main .xcodeproj and then add the library that the child .xcodeproj builds to the link in the main .xcodeproj.  Unfortunately it looks like mod-pbxproj currently doesn't have any support for this.

In analysing this I added a child .xcodeproj to my main .xcodeproj using project.add_file(), which treated it very naively, like any other file.

I then opened the main .xcodeproj in Xcode and it added a "projectReferences" field to the PBXProject object, PBXReferenceProxy objects for the outputs of the child .xcodeproj and a "Products" group under the child .xcodeproj group which reference those PBXReferenceProxy objects.  It would be good if mod-pbxproj could be made to mimic this behaviour in project.add_file() for .xcodeproj files, however there's currently not even a PBXReferenceProxy class so getting this working might be quite a bit of work.  Presumably it would also require analysing the child .xcodeproj to work out what files it builds.

Then if I add the library that the child .xcodeproj creates to the "Link Binary With Libraries" build phase in Xcode it adds a PBXBuildFile which references the relevant PBXReferenceProxy object and adds an entry to the "files" list in one of the PBXFrameworksBuildPhase objects.  It would be good to have some kind of API in mod-pbxproj to achieve this too.

**Comment by kronenthaler** [comment]
Thanks for your report, i will take a look at it.

**Comment by kronenthaler** [comment]
@markshep I have a PR(#159) open for the changes suggested in this ticket. It would be great if you could give it a go to see if it works for you as well. Branch name `nested-xcodeproj`
