### ISSUE TITLE
get_files_by_name()  get the wrong path

### ISSUE THREAD

**Issue by chenxi141017** [kronenthaler/mod-pbxproj#157]
I want to get the path from the file name , so I use this method to get a file 's path , the parameter of name I set `uuSdkConfig.json` , but the result of path is wrong, the result is like this  :

`{isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text.json; path = uuSdkConfig.json; sourceTree = "<group>"; }
`

the file actually is  like this  :
<img width="419" alt="2017-06-21 5 26 35" src="https://user-images.githubusercontent.com/14297268/27377818-a4085da4-56a8-11e7-912e-f0c02c2c7b97.png">

and my project is in below:
[project.pbxproj.zip](https://github.com/kronenthaler/mod-pbxproj/files/1091059/project.pbxproj.zip)

So, how to solve my problem ? Thank you

**Comment by kronenthaler** [comment]
Thanks for your report. However, it's on the documentation of the method you are using: 

```
Gets all the files references that have the given name, under the specified parent PBXGroup object or PBXGroup id.
```
The method returns a list of file references (PBXFileReference) objects, of which you can retrieve any of the attributes you printed out by doing:

```
files = project.get_files_by_name('name')
for file in files:
     print file.path
```
