### ISSUE TITLE
Is it possible to set attribute for existing framework?

### ISSUE THREAD

**Issue by rublevma** [kronenthaler/mod-pbxproj#160]
There is string in project.pbxproj:
`WatchConnectivity.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 593D4C848D10CAD146213F8B /* WatchConnectivity.framework */;`
How to set `{ATTRIBUTES = (Weak, ); }; `?

**Comment by kronenthaler** [comment]
Hello, 

The PBXBuildFile object has a public method called `add_attributes`, you can simply call it with 
`build_file.add_attributes('Weak')`

Now, there is a PBXBuildFile created for each target, so i would recommend to execute the following:

```
# locate the framework you want to add the attributes
for file_ref in project.get_files_by_name('WatchConnectivity.framework' ):
    # locate the PBXBuildFile that references that framework.
    for build_file in project.objects.get_objects_in_section('PBXBuildFile'):
        if build_file.fileRef == file_ref.get_id():
            # add the flag
            build_file.add_attributes('Weak')
```
Hope it helps

**Comment by rublevma** [comment]
Thank you very much!!!
