### ISSUE TITLE
Is it possible to modify Preprocessor Macros?

### ISSUE THREAD

**Issue by hxinle** [kronenthaler/mod-pbxproj#164]
![96ed6bea-fcfe-4a6d-a000-23a86e064119](https://user-images.githubusercontent.com/23518371/28100576-7aa2b22c-66f5-11e7-9168-869c3e5f8fe1.png)

**Comment by kronenthaler** [comment]
I haven't tried it myself, but i think you can simply execute this:

```
project.add_flags('GCC_PREPROCESSOR_DEFINITIONS', '<flag value>')
```

Optionally, check the [wiki](https://github.com/kronenthaler/mod-pbxproj/wiki/flags#flags) page for adding flags for extra options in the method.

**Comment by kronenthaler** [comment]
Closed due to inactivity.
