### ISSUE TITLE
ShellScript？？？

### ISSUE THREAD

**Issue by hahaGitHub** [kronenthaler/mod-pbxproj#165]
7F76FC5A93FE6A40A3D6BC3D /* [CP] Check Pods Manifest.lock */,
我没有做任何操作，project.save()之后，变为了7F76FC5A93FE6A40A3D6BC3D /* ShellScript */,
请问这是怎么回事呢？

**Comment by kronenthaler** [comment]
As i can't understand the "question" this ticket will be closed.
