### ISSUE TITLE
UnicodeDecodeError ascii

### ISSUE THREAD

**Issue by 99848873** [kronenthaler/mod-pbxproj#168]
File "/Users/zhoujinyu/Documents/QQCode/mod_project_test/pbxproj/openstep_parser/openstep_parser.py", line 148, in _parse_literal
    key += str[index]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)

i have an issue when i try to open an pbxproj file

**Comment by kronenthaler** [comment]
thanks for the report, it would help a lot if you post your project.pbxproj file to do some debugging.

**Comment by kronenthaler** [comment]
Closed due to lack of information
