### ISSUE TITLE
My Run Script was deleted by the mod-pbxproj

### ISSUE THREAD

**Issue by ParKTao** [kronenthaler/mod-pbxproj#172]
When I call the remove_files_by_path method, the file is deleted ,but my run script is gone too. Is it a bug or  my  fault,and how to fix it?

**Comment by kronenthaler** [comment]
Thanks for your report, this issue is probably related to the one fixed by #166 
Please update you python module to 2.1.1 and let me know if it solved you problem.

If not, please be more detailed of the steps to reproduce your issue or ideally provide sample project.pbxproj to work with.
