### ISSUE TITLE
Add third party library error when the library's path contain the whitespace

### ISSUE THREAD

**Issue by chenxi141017** [kronenthaler/mod-pbxproj#173]
when I add some third party to my project , and  the third party's path contains whitespace, it don't work well. such as the path is like this:
 `/Users/chenxi/Library/Application Support/Package/workspace`

I find the path split by the whitespace , the the path in the Xcode project show like this:
`/Users/chenxi/Library/Application` and `Support/Package/workspace` , I just modified you code  , and it works well , would you mind to fixed this bug? 

The code I modified is in the `XCBuildConfiguration.py` file. I just add a `\"` at the path's both ends

```
 def add_search_paths(self, key, paths, recursive=False, escape=False):
        if not isinstance(paths, list):
            paths = [paths]
        # build the recursive/escaped strings and add the flags accordingly
        flags = []
        for path in paths:
            # if contains whitespace, add the "\"" at both ends of the path
            if " " in path:
                path = '\"' + path + '\"'

            if path == '$(inherited)':
                escape = False
                recursive = False

            if escape:
                path = u'"{0}"'.format(path)

            if recursive and not path.endswith('/**'):
                path = os.path.join(path, '**')

            flags.append(path)

        self.add_flags(key, flags)
```

**Comment by kronenthaler** [comment]
thanks for the report, but your patch is not necessary. You can pass the parameter `escape=True` and it will do that for you.
