### ISSUE TITLE
How to add a folder to a project as select the option for "Create folder references"

### ISSUE THREAD

**Issue by chenxi141017** [kronenthaler/mod-pbxproj#175]
when I drag a folder to my project section , it will show me a dialog , I select the **Create folder references**,  then clicked the **Finish** button , it will add the folder to my project , and the folder's color is blue. So my problem is how to use the script to add a folder as I drag to my project?

**Comment by kronenthaler** [comment]
All info about how to create groups and references can be found here:
https://github.com/kronenthaler/mod-pbxproj/wiki/Groups-and-Folders#create-or-get-a-group

**Comment by chenxi141017** [comment]
@kronenthaler  thank you  very much!!! I got it.
