### ISSUE TITLE
Is it possible to add a file to multiple targets?

### ISSUE THREAD

**Issue by leoneparise** [kronenthaler/mod-pbxproj#176]
I'm developing a script to generate boilerplate code to my project. I have two targets (ag: Debug and Production) and I need to add files to these ones only. Right now we have the option to specify one target or add to all. Is it possible change the `target` to accept an array?

**Comment by kronenthaler** [comment]
Hello, thank you for the feedback. Right now make a change like that would mean a major refactor of multiple parts. I'm currently focusing efforts into stabilization and add missing Xcode related features. 

As for your problem, i think it would be pretty easy to work around the problem in your own script.

The most straightforward option i see, is to extract all the target-related operations into a function that receives the target name as parameter and create a for loop over the targets you want an call the extracted method for each.

```
def target_specific_operations(target_name):
  # do your thing

# operations over all targets

for target_name in ['Debug', 'Production']:
  target_specific_operations(target_name)

# more stuff over all targets
```

**Comment by bivanov** [comment]
So, basically, adding particular file to several targets can be achieved with: 

```
 for target_name in ['Debug', 'Production']:
      project.add_file(filename, force=False, t=target_name)
```     
?

Is it good approach?

**Comment by kronenthaler** [comment]
@bivanov if you want to be selective to what targets to add the file: yes. However, If those are your only 2 targets, it's done by default when you don't specify anything as target name.

**Comment by kronenthaler** [comment]
@bivanov Since the workaround doesn't meet the expectations,  here is another workaround that's possible but require calling private APIs. E.g.

```
targets = ['Debug', 'Production']
build_file = project.add_file(filename, force=False, target_name=target[0])
file_ref = build_file.fileRef

for target_name in targets[1:]:
     file_type, expected_build_phase = ProjectFiles._determine_file_type(file_ref, file_options.ignore_unknown_type)
     project._create_build_file(file_ref, target_name, expected_build_phase, file_options)
```

I will give it a thought about supporting target_name as single string, list or None in the future.

**Comment by bivanov** [comment]
@kronenthaler, thank you for reply. Trying to adapt code with proposed snippet:

```
def __add_to_project(project, filename, parent_group, targets=None):
    if targets:
        build_file = project.add_file(filename, force=False, target_name=targets[0])
        file_ref = build_file.fileRef

        for target_name in targets[1:]:
            file_type, expected_build_phase = ProjectFiles._determine_file_type(file_ref, file_options.ignore_unknown_type)
            project._create_build_file(file_ref, target_name, expected_build_phase, file_options)
    else:
        project.add_file(filename, force=False, parent=parent_group)
```

but if fails with 

`AttributeError: 'list' object has no attribute 'fileRef'`

Do I need to address to `build_file` as to list?

**Comment by kronenthaler** [comment]
yes, add_file will return always a list of the build file objects created (per target), even if there is only one target involved.

**Comment by kronenthaler** [comment]
i added the support for multiple targets on version 2.4.0. 

You can pass a list to target_name as: `target_name=[Debug, Production]`
