### ISSUE TITLE
Xcode9 - calling project.save() corrupts  pbxproj, size becomes 0 bytes

### ISSUE THREAD

**Issue by subzeroiosguy** [kronenthaler/mod-pbxproj#178]
I was just trying out basics- running Xcode9- when I calll project.save(), my pbxproj size becomes 0 bytes, making it unusable. 

```
from pbxproj import XcodeProject

project = XcodeProject.load('/Users/brajb/ios_core/ios.xcodeproj/project.pbxproj')
framework = project.get_or_create_group('fframework')
project.save()
```

**Comment by kronenthaler** [comment]
Thanks for your report. I will investigate

**Comment by kronenthaler** [comment]
I have been trying to reproduce the issue without success. I wonder what version of the library are you using.
Please check the versions using: 

```
pip list | grep pbxproj
```

and 


```
pip list | grep openstep-parser
```

You should be running pbxproj 2.1.2 and openstep-parser 1.3.0. If not you need to upgrade and try again.

**Comment by kronenthaler** [comment]
Closed due to the lack of input and unable to reproduce

**Comment by vbraun** [comment]
But there is a race, the save method just does an open/write/close. This is not atomic, so if you are unlucky then xcode sees a half-written project.pbxproj and helpfully fixes it for you. Which is then clobbered some more as you keep writing to it. 

The POSIX method to replace a file atomically is 
1) write to a temp file on the same filesystem (usually, same directory) and then 
2) move the temp file to the target.
