### ISSUE TITLE
'PBXBuildFile' object has no attribute 'fileRef'

### ISSUE THREAD

**Issue by erdnussflips** [kronenthaler/mod-pbxproj#179]
I have the problem, if the module is adding flags and the project.pbxproj has errors like 
> 9D1494321F73F8AB0078CFF8 /* (null) in Sources */ = {isa = PBXBuildFile; };

i'm getting

> 'PBXBuildFile' object has no attribute 'fileRef'

Is it possible to ignore these entries, or to remove this entries automatically from the file?

**Comment by kronenthaler** [comment]
Thanks for your report. I don't consider it a bug that pbxproj fails if the project is malformed in the first place. 
It could be an improvement to implement what you suggested (delete malformed entries), however this might require a lot of work as there is no official documentation of what parameters are mandatory on each section/phase.

For your particular case, i think is more important to fix what is corrupting the project.pbxproj file and fixed. If the culprit happens to be another pbxproj command, please let me know.

**Comment by ErdnussFlipS** [comment]
Ok, I understand your point of view, but Xcode is tolerant enough to ignore this error. In other words, this error was created by Xcode.

I think, pbxproj should be as same tolerant as Xcode.

Can you identify where

> 'PBXBuildFile' object has no attribute 'fileRef'

is logged?

**Comment by kronenthaler** [comment]
You should have a stacktrace together with that line, It's a generic python exception. Are you trying to add the flags using the CLI or embedded into a python script?

It would help me more if you could post the project.pbxproj and the commands/script you are trying to execute that leads to this error. Please redact any filenames if you consider it necessary.

**Comment by ErdnussFlipS** [comment]
Sorry for the late response.
I tried to add flags using CLI.

`python -m pbxproj flag -t "pbxproj" "pbxproj.xcodeproj/project.pbxproj" -- OTHER_CFLAGS '-flagName' OTHER_CFLAGS "flagValue"`
> Flags added successfully.
> 'PBXBuildFile' object has no attribute 'fileRef'

[pbxproj.zip](https://github.com/kronenthaler/mod-pbxproj/files/1883980/pbxproj.zip)

**Comment by Navimark** [comment]
The same problem to me.
But after I use [xUnique](http://www.mokacoding.com/blog/xunique/) to have my `.pbxproj` file trimmed,`XcodeProject` parser the `.pbxproj` like a charm. @ErdnussFlipS you may have a try.

**Comment by Usipov** [comment]
For me the problem was in `project.pbxproj` referencing a non-existing file. That reference was replaced by `XcodeProject` tool with a currupted `PBXBuildFile`, so I quickly found the problem-causing line and removed it
