### ISSUE TITLE
UnicodeDecodeError ascii

### ISSUE THREAD

**Issue by weiss19ja** [kronenthaler/mod-pbxproj#181]
As mentioned in a issues before, the library throws a Exception while parsing the project if it contains any non ascii characters.
For instance if it would use german special characters like "ä", "ö", "ü", "ß". If you would read the project.pbxproj file as unicode string this exception would not happen.
This is a issue because xcode supports any UTF-8 characters like language specific special characters.

**Comment by kronenthaler** [comment]
Duly noted, however the reading of the project file doesn't belong to this github project but to https://github.com/kronenthaler/openstep-parser

**Comment by weiss19ja** [comment]
You are right, but you could use the ParseFromString method instead the ParseFromFile from the OpenStepDecoder. In this case you could pass a utf-8 decoded string to the parser.
I created a pull request for this issues. It would be kind of you if you could take a look at it.
