### ISSUE TITLE
 Why do not always build it？

### ISSUE THREAD

**Issue by Dreamhai** [kronenthaler/mod-pbxproj#186]
hi，
I use this code：
project.add_file('projectfile/PGTools.h',parent=Second,force=False)   there is something wrong?

but I use this code can build it:
project.add_file('projectfile/PGTools.h',force=False)

One less parameter：parent
 so  Can you give a complete example?
thanks

**Comment by kronenthaler** [comment]
Have you checked the documentation of the [add_file](https://github.com/kronenthaler/mod-pbxproj/wiki/files) function. Parent must be a `PBXGroup` object, you can get or create the group using [this](https://github.com/kronenthaler/mod-pbxproj/wiki/Groups-and-Folders#create-or-get-a-group).

If this doesn't solve your problem i will need more input. Ideally, a sample project to work with.

**Comment by Dreamhai** [comment]
thanks
