### ISSUE TITLE
How do I choose a group where I add file with CLI?

### ISSUE THREAD

**Issue by ynechaev** [kronenthaler/mod-pbxproj#199]
I am trying to use CLI and add file to a project as following:
```bash
pbxproj file Foo.xcodeproj/project.pbxproj Foo/Bar/FooBar.h --target Foo
```
But the file is added to the root of the project. Is there any way to specify a group where file is added?

**Comment by kronenthaler** [comment]
Thanks for your report. That feature is not available yet.
