### ISSUE TITLE
Adding files to different targets in loop results in several mentions of same file in project structure

### ISSUE THREAD

**Issue by bivanov** [kronenthaler/mod-pbxproj#207]
As discussed [here](https://github.com/kronenthaler/mod-pbxproj/issues/176) it should be possible to add same file to several targets with next code:

```
 for target_name in ['Debug', 'Production', 'AppStore', 'Staging']: #etc
      project.add_file(filename, force=True, t=target_name)
```     

(Note: `force=False` will add file only to first target in list)

This code works but there is problem. File added this way will appear in project tree separately for each target. So, given I'm adding file with name "MyBeautifulController.swift" to project to targets 'Debug' and 'Release', I will have two files named "MyBeautifulController.swift" in project tree, one is related to 'Debug' target and another to 'Release' one (on disk this is one and same file, of course).

**Comment by kronenthaler** [comment]
@bivanov you are correct. I think this ticket is a duplicated from the #176. I will close the ticket and continue the conversation in the other thread.
