### ISSUE TITLE
How add a framework in `Build Phases` -> `Copy Files`

### ISSUE THREAD

**Issue by chenxi141017** [kronenthaler/mod-pbxproj#217]
In my project, I need add a 3rd framework in to `Link Binary With Libraries` and also add it into `Copy Files` as well, is there any way to resolve my problem?

**Comment by kronenthaler** [comment]
Hello, have you checked this page: https://github.com/kronenthaler/mod-pbxproj/wiki/files#add-a-libraryframework?

If that doesn't solve your problem please reopen the ticket, and provide:
- a sample project to reproduce the issue
- steps to reproduce the issue
