### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by realityJie** [kronenthaler/mod-pbxproj#218]
I need to remove framwork, bundle and staticLib from xocde，but there is no API what i can call. The project provide `remove_files_by_path`API, but it just can remove file like *.m or *.h.

**Comment by kronenthaler** [comment]
Hello, there no separated API for removing frameworks. You can use the same API to remove a framework. If this is not working as expected, please provide a sample project and the steps to reproduce the issue.

**Comment by kronenthaler** [comment]
duplicates #223
