### ISSUE TITLE
Add flags to project as well (not only to targets)

### ISSUE THREAD

**Issue by nikolamajcen** [kronenthaler/mod-pbxproj#219]
Hi,

I have a question about adding flags to an iOS project.
I've successfully added flags to multiple targets and configurations, but is there a way to add those flags to project as well? So, project will have those flags and targets will inherit them. 

Currently, if flags are added to all targets, every target has those flags, but the project does not have them. I know that target flags overrides project flags, but it would be good if that functionality is available.

**Comment by kronenthaler** [comment]
released in 3.2.0
