### ISSUE TITLE
Unknown file extension: .wav. Please add the extension and Xcode type to ProjectFiles._FILE_TYPES

### ISSUE THREAD

**Issue by kokizzu** [kronenthaler/mod-pbxproj#221]
what should i add on `ProjectFiles._FILE_TYPES`?

**Comment by kokizzu** [comment]
nevermind, i think this one the solution `u'.wav': (u'audio.wav', u'PBXResourcesBuildPhase'),`

**Comment by osfunapps** [comment]
a better approach:
`ProjectFiles._FILE_TYPES[u'.wav'] = (u'audio.wav', u'PBXResourcesBuildPhase')`

Keep your external libs safe 😸
