### ISSUE TITLE
add_file returns prematurely if the file already exists with different target with force=False param

### ISSUE THREAD

**Issue by ynechaev** [kronenthaler/mod-pbxproj#225]
## Problem
The problem appears during the `ProjectFiles.add_file` usage with `target` specified and when that particular file already exists under different target, which causes the return prematurely.

## Approach
By default `force` option is enabled for better backward compatibility, but it will generate duplicates if I run this command for the same file multiple times. In other words, I want it to be disabled, so the invocation will look like the following:
```python
project.add_file(file, target_name=target, parent=parent_group, tree="<group>", force=False)
```
## Result
If the file is already presented in project, for example in a test target, the execution will drop at a point where the file reference is found in a project.
## Desired result
The desired outcome in this case would be checking if the existing file's target equals to the provided one and if not, add it with the provided target.

**Comment by kronenthaler** [comment]
Thanks for your report. Although the report is valid, you could add the same file to multiple targets in one single invocation, by providing as `target_name` a list of all the targets where the file needs to be added to. 

I will address the issue nonetheless.
