### ISSUE TITLE
AttributeError: class XcodeProject has no attribute 'load'

### ISSUE THREAD

**Issue by megatronxx** [kronenthaler/mod-pbxproj#227]
Traceback (most recent call last):
  File "/Users/mac/Desktop/WFPyProjs/main.py", line 20, in <module>
    project = XcodeProject.load('/Users/***/Desktop/pydemo/pydemo.xcodeproj/pydemo.pbxproj')
AttributeError: class XcodeProject has no attribute 'load'

**Comment by kronenthaler** [comment]
Hello, it looks like you are not importing the right file or you have the old version.

Check that you had installed a version 3.x.x if you used pip.

You can also check the wiki for information about how to import the right module.
