### ISSUE TITLE
How to set folder path same with name while add folder?

### ISSUE THREAD

**Issue by cuiYuhe** [kronenthaler/mod-pbxproj#230]
Dear kronenthaler,
The folder is added in absolute path, is there a way to set the path of the folder same with name? 
Thanks.

**Comment by kronenthaler** [comment]
Thanks for your question. When adding folders, you can control how do you want them added; as groups or as references. If added as groups, the name will match the component of the path.

Could you provide with an example of what exactly is the desired end result and what is the current one?
