### ISSUE TITLE
How to add "input Files" "output Files" when adding "Run Script"

### ISSUE THREAD

**Issue by nrikiji** [kronenthaler/mod-pbxproj#233]
I would like to add "input Files" "output Files" when adding "Run Script" of "Build Phases", but please tell me if there is any way

**Comment by kronenthaler** [comment]
Hello, there is no public API to do so right now, but the underlying parts needed are in place. I will mark this request as an enhancement.

**Comment by nrikiji** [comment]
Thank you very much. I'm expecting you!

**Comment by kronenthaler** [comment]
To be release at 3.2.0
