### ISSUE TITLE
Adding configurations and targets

### ISSUE THREAD

**Issue by gregersn** [kronenthaler/mod-pbxproj#234]
Is it possible to add configurations and/or targets to a project?

**Comment by kronenthaler** [comment]
Short answer: not out-of-the-box, but manually.

Long answer: Technically is possible, but you will need to create each entity manually and add them to the project on the right places. For instance a target, has build configurations and build phases, you can create each one of these entities manually and add them to the project. 

It's on the future plans to add the ability to spawn projects from scratch, so this is a very critical component on that use case.
