### ISSUE TITLE
The save operation took about 10 minutes

### ISSUE THREAD

**Issue by sunsetroads** [kronenthaler/mod-pbxproj#247]
`
_project = XcodeProject.load('/Users/mj/work/xltemp/xltemp.xcodeproj/project.pbxproj')
_project.save()
`
This xcode project is exported by untiy，It has a lot of files. The save operation took about 10 minutes even if what also didn't do, Is there a way to optimize to save time?

**Comment by kronenthaler** [comment]
Thanks for your question. It would help to know a rough estimated of the amount, 100, 1000, 10000, 100000?

**Comment by znvy** [comment]
Around 20000

**Comment by kronenthaler** [comment]
One more bit, are they mostly source code files, resources, frameworks, other?

**Comment by znvy** [comment]
Mostly files are .h and .cpp code, it is generated by untiy. Path  is /Users/mj/work/xltemxltemp/Classes/Native， Untiy export projects usually have this folder
