### ISSUE TITLE
How to get the name of target dependencies?

### ISSUE THREAD

**Issue by PeterPan4d** [kronenthaler/mod-pbxproj#248]
Hi, I have the following code snippet and get a PBKey back, but how do I get the name of that dependency?

```
key = p.get_target_by_name("AllTargets").dependencies[0]
print(type(key)) # PBKey
```

Thanks!

**Comment by kronenthaler** [comment]
Thanks for your question. Once you retrieve the key, you need to follow the trail.
You can now use that key to retrieve the object it points to, with

```
p.get_object(key)
```

This will return you the object that it's pointing to. Normally, this is a `PBXTargetDependency`, which contains a `target` property, which is another key, that points to a `PBXNativeTarget` (this is your actual dependency).

So, it would be something like this:
```
target_dependency = p.get_object(key)
target_key = p.get_object(target_dependency.target)
target = p.get_object(target_key)
print(target.name + " / " +target.productName)
```
