### ISSUE TITLE
Exception in:PBXGenericObject _format method

### ISSUE THREAD

**Issue by yiwangwuqian** [kronenthaler/mod-pbxproj#252]
In _format method,last else statement:
>else:
>>value = PBXGenericObject._escape(value.__str__(), exclude=[u"\'"])

Here first parameter,`value.__str__()`,when value is type unicode will be occur exception.

My solution for reference only:
>else:
>>if isinstance(value,unicode):  
>>>value = PBXGenericObject._escape(value, exclude=[u"\'"])

>>else:
>>>value = PBXGenericObject._escape(value.__str__(), exclude=[u"\'"])

**Comment by kronenthaler** [comment]
Thanks for your report. Soon i will be removing support for python2 since it will reach EOL in Jan 2020. This issue should go away or be fixed when that happens.
