### ISSUE TITLE
How to show the system framework?

### ISSUE THREAD

**Issue by Kratos28** [kronenthaler/mod-pbxproj#255]
How to  get show the system framework? not contain show third framework
![屏幕快照 2020-01-09 上午11 15 17](https://user-images.githubusercontent.com/8486246/72035067-c1406d00-32d1-11ea-8def-0f553ce4ad5a.png)

**Comment by kronenthaler** [comment]
Thanks for your report. Could you clarify what is your desired outcome?

**Comment by Kratos28** [comment]
Thanks you  reply 
i want desired outcome  similar

CLI 
pbxproj  show  (--target <target>...) <project> -f

**Comment by kronenthaler** [comment]
Thanks for coming back.
For what i have tested, the command that you specified does what you want
```
pbxproj show ~/Downloads/test/test.xcodeproj/project.pbxproj --target test -f
test:
        Product name: test
        Frameworks: 
                AVFoundation.framework
                AdSupport.framework
                CoreData.framework
                CoreMedia.framework
                SwiftUI.framework
```

As you can see all of those frameworks are system frameworks and they are displayed based on what is configured in the project.

**Comment by Kratos28** [comment]
Thanks you reply
CIL pbxproj show ~/Downloads/test/test.xcodeproj/project.pbxproj --target test -f
contain third framework,I don't want to show a third framework

**Comment by kronenthaler** [comment]
In this point i don't understand the question anymore. i'm not sure if you want to limit the output, exclude something or something is wrongly being displayed.

Could you provide a text of the current output **you** are getting when you execute the `pbxproj show` command, and an example of what you want to see. And please include the `pbxproj show` full command that you would like to be executing to obtain the desired output.

**Comment by Kratos28** [comment]
Thanks you reply
I don't want to show third-party libraries, just show system

**Comment by Kratos28** [comment]
Thanks you reply
I don‘t want to show 3rd party libraries,just show system libraries.
<img width="794" alt="DFA9227C-9BDA-4065-A051-C20D3BD98C95" src="https://user-images.githubusercontent.com/8486246/73606821-4412ca00-45e9-11ea-8688-6f0da379f247.png">
