### ISSUE TITLE
How to modify TargetAttributes

### ISSUE THREAD

**Issue by JanNovakFRI** [kronenthaler/mod-pbxproj#261]
Hello,

is it possible to modify `TargetAttributes` properties. More specifically I would like to add `DevelopmentTeam` to `TargetAttributes` and set it's value.

Thanks in advance

**Comment by kronenthaler** [comment]
Thanks for your question. Technically, you can, but there is no convenience API at the moment to do that for you. It is possible but you will need to do all the plumbing. 

For starters, you need to retrieve the `PBXProject` object, in this object you will set the `TargetAttributes` as `project_obj.attributes.TargetAttributes[<targetId>] = { ... }`

Where `<targetId>` is the unique identifier of the target where you want to apply the attribute.
Lastly, The object that you will be assigning it depends on the attributes you want to assign. 

My overall recommendation is to create a sample project in xcode (as basic or empty as possible), copy the `*.xcodeproj/project.pbxproj` file somewhere safe, apply the changes and compare them against the original file you saved (potentially using a diff tool).

**Comment by JanNovakFRI** [comment]
Thank you for answer. By looking at source code I managed to write helper function, that does job for me. Here is the snippet if someone finds it useful:

```
class FooClass:
    def __init__(self, project_path):
        self.project = XcodeProject.load(project_path)

    def example_function(self):
        # Sample use of helper function

        self.set_target_attributes(
            target="Runner", data={
                "DevelopmentTeam": development_team
            }
        )

    def set_target_attributes(self, target, data):
        for obj in self.project.objects.get_objects_in_section('PBXProject'):
            for index, t in enumerate(obj.targets):
                target_name = self.project.objects[obj.targets[index]].name
                o = obj.attributes.TargetAttributes[t]
                if target_name == target:
                    for key, value in data.items():
                        o[key] = value
```
