### ISSUE TITLE
Question: how to add per-file compiler flags?

### ISSUE THREAD

**Issue by garvankeeley** [kronenthaler/mod-pbxproj#27]

**Comment by garvankeeley** [comment]
The answer is 
`result = XCodeProject.add_file(...)`
`for item in result:`
`     ``if isinstance(item, PBXBuildFile): item.add_compiler_flag(...)`

**Comment by kronenthaler** [comment]
Thanks, i didn't have time to check this in detail.
I'll update the Readme to include this kind of common tasks.

**Comment by fadookie** [comment]
I'm still not sure how to do this for files that are already in the project rather than ones I'm trying to add. Also, this was never added to the readme. :)

**Comment by fadookie** [comment]
OK I figured it out, here's an example for others:
```python
def disableArc(filePath):
    fileId = project.get_file_id_by_path(filePath)
    files = project.get_build_files(fileId)
    for f in files:
        f.add_compiler_flag('-fno-objc-arc')

disableArc('Libraries/Plugins/iOS/JSONKit.m')
```

**Comment by kronenthaler** [comment]
Cool you figure it out! Could i ask you to make a PR with the snippet on
the readme? XD

**Comment by fadookie** [comment]
Done: https://github.com/kronenthaler/mod-pbxproj/pull/82
