### ISSUE TITLE
I got a problem

### ISSUE THREAD

**Issue by yuhe1989** [kronenthaler/mod-pbxproj#271]
this is my code:
from pbxproj import XcodeProject

#project path
projectPath = '/Users/ameng/Desktop/packagetest/file/PackageTest/PackageTest.xcodeproj/project.pbxproj'
# open prohect
project = XcodeProject.load(projectPath)
#  add file
project.add_folder("/Users/ameng/Desktop/packagetest/file/test")
#project.add_file("")

# save
project.save(projectPath)

The 'test' file was added into the project, but when I build the project occurred an error:【 library not found for -lCTMediator】.And I am sure this error occurred after used XcodeProject, I have tried many times, got the same error . The 'CTMediator' is managed with Pod.

**Comment by kronenthaler** [comment]
Thanks for reaching out. However the information provided is not enough to do any debugging.
I recommend the following steps to be able to look further:
1. Create a sample project, isolating the issue you have. By sample project i mean a project with the minimum amount of files to be able to reproduce your issue consistently and without sharing your actual project. In other words, try to create a dummy project that reflects your problem.
2. Provide the script and the expected outcome you are looking for.
