### ISSUE TITLE
[BUG] Cannot automatically delete references in Xcode after deleting the specified resource

### ISSUE THREAD

**Issue by wangweilucky** [kronenthaler/mod-pbxproj#273]
**Describe the bug**
Cannot automatically delete references in Xcode after deleting the specified resource

**System information** 
project = XcodeProject.load(projectPath)
project.remove_files_by_path(img2x)

**Comment by kronenthaler** [comment]
Thank you for your report. Can you provide the requested info in the template?

* Xcode version
* pbxproj version
* Steps to reproduce the issue, including initial setup, and expected outcome
