### ISSUE TITLE
Is there a way to edit the Schemes?

### ISSUE THREAD

**Issue by Mach1Studios** [kronenthaler/mod-pbxproj#284]
Is there a way to edit/add/remove Schemes, can be something simple as just setting the Executable to none so we can change to a non-runtime build type without error

**Comment by kronenthaler** [comment]
Thanks for your inquiry. Schemes are external entities to the pbx projects. They live in the context of an Xcode project, but they have nothing to do with the entities that are manipulated on this python library. 

Adding support for schemes would break the spirit and purpose of this library, as it implies doing manipulations in the filesystem itself outside of the project file. Plus adds many more responsibilities to this library to maintain and keep neatly coupled.
