### ISSUE TITLE
[BUG] Error in openstep_parser: string index out of range

### ISSUE THREAD

**Issue by VitorMMOliveira** [kronenthaler/mod-pbxproj#292]
**Describe the bug**
I'm trying to use the default sample code on the homepage just to check how mod-pbxproj works, however I stumbled upon this error:

Traceback (most recent call last):
  File "xcode_python_setup.py", line 3, in <module>
    project = XcodeProject.load('../myapp/myapp.xcodeproj/project.pbxproj')
  File "/Library/Python/2.7/site-packages/pbxproj/XcodeProject.py", line 90, in load
    tree = osp.OpenStepDecoder.ParseFromFile(open(path, 'r'))
  File "build/bdist.macosx-10.15-x86_64/egg/openstep_parser/openstep_parser.py", line 42, in ParseFromFile
  File "build/bdist.macosx-10.15-x86_64/egg/openstep_parser/openstep_parser.py", line 46, in ParseFromString
  File "build/bdist.macosx-10.15-x86_64/egg/openstep_parser/openstep_parser.py", line 51, in _parse
IndexError: string index out of range

**System information** 
1. pbxproj version used: 3.2.0
2. python version used: 3.6.12
3. Xcode version used: 12.0 (12A7209)

**To Reproduce**
1. Created a .py file with this code

from pbxproj import XcodeProject
project = XcodeProject.load('../myapp/myapp.xcodeproj/project.pbxproj')
project.save()

2. On the terminal, cd to a related folder and ran: "python xcode_python_setup.py"
3. See error

**Expected behavior**
Just expected to see a clear python command without any errors.

**Comment by kronenthaler** [comment]
Thanks for your report

Looking at the stacktrace it may seem that the wrong python package is running, the python 2.7 version of it.

> File "/Library/Python/2.7/site-packages/pbxproj/XcodeProject.py", line 90, in load
tree = osp.OpenStepDecoder.ParseFromFile(open(path, 'r'))

In the code, the [line 90](https://github.com/kronenthaler/mod-pbxproj/blob/master/pbxproj/XcodeProject.py#L90) is something else:

> targets = self.objects.get_targets(name)

Double check by installing the package using `pip3` and running it with `python3` command.

**Comment by kronenthaler** [comment]
Thanks for trying out. 

Could you share the sample project to check it manually? I'd only need the project.pbxproj file.

**Comment by VitorMMOliveira** [comment]
Sorry, unfortuntely I can't due to NDAs.

But maybe I could check it on my machine if I have the instructions, and then share the results here.

**Comment by kronenthaler** [comment]
Understood. 

Index out of range would point me to the end of the file. It looks like a unclosed something, or a broken comment.

**Comment by VitorMMOliveira** [comment]
Solved! Thanks for the input.

I checked the pbxproj file and it was empty. Probably due to some other error in the past.
I just reverted the changes on git and it works fine now with python3. Thank you for the support!
