### ISSUE TITLE
[BUG] invalid syntax  ret = f"{'{'}{object_start}" , Python 2.7.16

### ISSUE THREAD

**Issue by TiagoMJFlores** [kronenthaler/mod-pbxproj#294]
Hi,

**System information** 
1. pbxproj version used: last version
2. python version used: 2.7.16
3. Xcode version used:12

I am getting the following error:
![image](https://user-images.githubusercontent.com/7196556/102727119-aec11700-431b-11eb-814a-a3e7f6eb3f68.png)

What I can do?

Thanks

**Comment by kronenthaler** [comment]
Thanks for your report. Please check that you are using python3 and the package version installed using pip3.

Python 2 is end of life and out of support.
