### ISSUE TITLE
Remove file by path feature request

### ISSUE THREAD

**Issue by BuXY** [kronenthaler/mod-pbxproj#32]
Hi there,

nice script! Although i have been missing the remove file feature, it was only possible with its UUID known. So i came up with my solution. You can improve / include it freely.

    def get_file_id_by_path(self, f_path):
        for k, v in self.objects.iteritems():
            if str(v.get('path')) == f_path:
                return k
        return 0

    def remove_file_by_path(self, f_path, recursive=True):
        id = self.get_file_id_by_path(f_path)
        if id != 0:
            self.remove_file(id, recursive=recursive)
        return

Cheers,
BuXY

**Comment by kronenthaler** [comment]
I will happily merge it if the pull request is made for it.
