### ISSUE TITLE
[BUG] Update multible Flags

### ISSUE THREAD

**Issue by mklarsen** [kronenthaler/mod-pbxproj#323]
Trying to update ALL IPHONEOS_DEPLOYMENT_TARGET from 9.0 to 12.0

**System information** 
pbxproj version used: pbxproj  3.4.0
python version used: Python 3.10.6
Xcode version used: xCode Version 14.0.1 (14A400)

**To Reproduce**
Installed pbxproj
>pip3 install pbxproj

created "update_pbxproj.py"
````bash
from pbxproj import XcodeProject
# open
project = XcodeProject.load('ios/Runner.xcodeproj/project.pbxproj')

# set variables
project.set_flags('IPHONEOS_DEPLOYMENT_TARGET', '12.0')

# save
project.save()
````

run script  
````bash
python3 update_pbxproj.py
````
after open then ios/Runner.xcodeproj/project.pbxproj
still have IPHONEOS_DEPLOYMENT_TARGET = 9.0;

**Expected behavior**
Every flags IPHONEOS_DEPLOYMENT_TARGET = 12.0;

**Screenshots**

**Comment by kronenthaler** [comment]
Thanks for the report. Could you attach a sample project? only the `project.pbxproj` file is necessary.
