### ISSUE TITLE
Unity 5 Xcode project and Library Linking

### ISSUE THREAD

**Issue by jp-at-grantoo-org** [kronenthaler/mod-pbxproj#34]
I've noticed that for the Xcode (v6.2) projects generated by Unity 5 (v5.0.0f4) `add_file_if_doesnt_exist()` no longer appears to be adding some frameworks to the list of libraries linked with the binary under the Build Phases tab of the Xcode project.  The references to the frameworks to be added exist under the `PBXFileReference` section of the *project.pbxproj* but they don't exist under the `PBXBuildFile` section.  I've seen this when adding the AdSupport.framework:

```python
project_path = '<project_path>/Unity-iPhone.xcodeproj/project.pbxproj'
framework_path = '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/AdSupport.framework'
framework_group = project.get_or_create_group('Frameworks')
project = XcodeProject.Load(project_path)
project.add_file_if_doesnt_exist(framework_path, tree='SDKROOT', parent=framework_group )
```

The *create_build_files* argument defaults to **True** and the *weak* argument defaults to **False**.

I think what's happening is that only the objects under the `PBXFileReference` section of the *project.pbxproj* are being checked for the existence of the framework in the project where it should instead be checking both the reference and build sections.  I believe that `add_file_if_doesnt_exist()` should work like the following:

```
if (framework exists in PBXFileReference) {
    if (create_build_files == true) {
        if (!framework exists in PBXBuildFile) {
            create build files entry in project.pbxproj for the framework
        }
    }
    return []  // not sure about this in the case that the build files entry is added
}
return result from calling add_file()       
```

**Comment by kronenthaler** [comment]
I will take a look, but i think the problem could be related to the way new frameworks work. Now frameworks are not a static library in a specific folder structure, they need to be 'embedded' into the project, meaning they have to be included in 2 places (or at least in the UI they are added in 2 different places at the same time)

**Comment by kronenthaler** [comment]
I think i spotted the problem. In your example you are trying to use the project BEFORE it's loaded:
```
framework_group = project.get_or_create_group('Frameworks')
project = XcodeProject.Load(project_path)
```
I assume you opened the project somewhere else and then reopen it (don't know why), but then when adding the file, it is being added in another instance of the project that won't be persisted when you save the second opened project.

A note: It's always recommended to not use absolute paths, for the system frameworks you can use 
`System/Library/Frameworks/AdSupport.framework` Notice the lack of the slash at the beginning.

**Comment by jp-at-grantoo-org** [comment]
Sorry, you're correct.  That was my mistake in cutting/pasting from my working code.  The code sample should have been:

```
project_path = '<project_path>/Unity-iPhone.xcodeproj/project.pbxproj'
framework_path = '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/AdSupport.framework'
project = XcodeProject.Load(project_path)
framework_group = project.get_or_create_group('Frameworks')
project.add_file_if_doesnt_exist(framework_path, tree='SDKROOT', parent=framework_group )
```

However, the issue is still occurring.

I have created a pull request (https://github.com/kronenthaler/mod-pbxproj/pull/44) on the modifications that I have made to the mod_pbxproj.py script that have allowed the libraries/frameworks/sources to be added properly to the Xcode project generated by Unity 5.

**Comment by kronenthaler** [comment]
Could you send me a project file created by Unity 5 to test some other cases too?

**Comment by jp-at-grantoo-org** [comment]
Will the default Xcode project generated from the default Unity
project/scenes be sufficient?

On Mon, May 4, 2015 at 1:07 PM, Ignacio Calderon <notifications@github.com>
wrote:

> Could you send me a project file created by Unity 5 to test some other
> cases too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kronenthaler/mod-pbxproj/issues/34#issuecomment-98835050>
> .
>



-- 
*Jan-Paul Azucena*
SDK & Integrations Engineer
skype: oO_SwooP_Oo
jp@fuelpowered.com

**Comment by kronenthaler** [comment]
Yes, i just need the starting skeleton to test your changes against, and to compare the differences with a new xcode's one.

**Comment by jp-at-grantoo-org** [comment]
Here's the default project.pbxproj.  One of the first things that I noticed
that didn't look correct from the generated project was that the
AdSupport.framework PBX file reference was added but did not have the
PBXBuildFile entries.

On Mon, May 4, 2015 at 1:56 PM, Ignacio Calderon <notifications@github.com>
wrote:

> Yes, i just need the starting skeleton to test your changes against, and
> to compare the differences with a new xcode's one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kronenthaler/mod-pbxproj/issues/34#issuecomment-98847667>
> .
>



-- 
*Jan-Paul Azucena*
SDK & Integrations Engineer
skype: oO_SwooP_Oo
jp@fuelpowered.com

**Comment by kronenthaler** [comment]
mm there was not attachment, github must have removed it from the email. Could you paste it in a [gist](https://gist.github.com/)

**Comment by jp-at-grantoo-org** [comment]
Here's you go, try this:
https://gist.github.com/jp-at-grantoo-org/4484d5e7e02bf1d7ec6c

On Mon, May 4, 2015 at 2:09 PM, Ignacio Calderon <notifications@github.com>
wrote:

> mm there was not attachment, github must have removed it from the email.
> Could you paste it in a gist <https://gist.github.com/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kronenthaler/mod-pbxproj/issues/34#issuecomment-98850448>
> .
>



-- 
*Jan-Paul Azucena*
SDK & Integrations Engineer
skype: oO_SwooP_Oo
jp@fuelpowered.com

**Comment by kronenthaler** [comment]
I have been playing around with the project you pasted. And i couldn't reproduce your error. 
The framework is added in the right build phases and for all the targets. 
I tested it with relative and absolute paths. The framework is marked in all targets in all correct build phases.
I won't merge the changes until i can verify the behavior with a copy of Unity 5, but i won't close the pull request in the meantime either.

**Comment by kronenthaler** [comment]
So, i got my copy of unity 5 and generated a empty project. And i saw that AdSupport.framework was already added to the source files tree, BUT not in the targets. 
I deleted the file and re-added it worked just fine. No changes need to the source code.

Here the example i'm running:
```
from mod_pbxproj import XcodeProject
import sys
import os

proj = XcodeProject.Load(sys.argv[1] + '/Unity-iPhone.xcodeproj/project.pbxproj')
proj.remove_file_by_path('System/Library/Frameworks/AdSupport.framework')
frameworks = proj.get_or_create_group('Frameworks')
proj.add_file_if_doesnt_exist('System/Library/Frameworks/AdSupport.framework', tree="SDKROOT", parent=frameworks)
proj.save()
```

call using:
```
$> script path/to/project
```

**Comment by ekilah** [comment]
@kronenthaler Hi, just to clarify (google brought me here because you said `"embedded"` earlier in this post): can the current version of this project add third-party dynamic frameworks (new to iOS 8) to Xcode's "Embedded Binaries" section? it seems like this issue was closed, but I can't tell if the OP was really asking about this feature or not.

**Comment by kronenthaler** [comment]
Short answer, not on a single call.
It's possible but it needs some extra code to be done, i haven't done it myself otherwise i'd post the example.
Currently i'm rewriting the whole project to make it more modular, future proof, easy to update and testable. This is definitively going to be on the new version, but i'm not putting a deadline on it as i do this on my spare time.

**Comment by ekilah** [comment]
Thanks for the reply. I look forward to the update, whenever that may be - and in the meantime, if anyone has a code sample for this use case i'd be thankful!

**Comment by HassanAliCTech** [comment]
any update on "Embedded Binaries"?

**Comment by kronenthaler** [comment]
Yes, version 2.0 is already publicly available, the new API for adding files supports options via the FileOptions class' embed_framework flag. By default this value is True.
So, in 2.0, simply add your file using the add_file API. Check https://github.com/kronenthaler/mod-pbxproj/wiki/files for details.
