### ISSUE TITLE
How to add a file/folder for a specific target ?

### ISSUE THREAD

**Issue by Drusy** [kronenthaler/mod-pbxproj#36]
Hello,

Thank for your script, it works like a charm. 
Being able to add files and references to my project, I would love to add a file for a specific target.
The following code is adding the files to all my targets (for example the main one and the Test one).

    for phase in phases:
        build_file = PBXBuildFile.Create(file_ref, weak=weak)

        phase.add_build_file(build_file)
        results.append(build_file)

My problem is that I am not able to find anything in the phase object that can be linked to a target name.
I am missing something ?

Thanks in advance.

**Comment by kronenthaler** [comment]
You can take a look at the `add_run_script` it receives a target name as parameter and looks for all targets to add the run script to a single target. I think you could filter directly against 
```
if phase.get('name') == target :
```

**Comment by Drusy** [comment]
I already checked `phase.get('name')` but it just give me `None`.
I print the whole Phase and I found any relation to a Target, not a Name, nor an ID, only the contained files.

The answer is in the `add_run_script`, thank you !

**Comment by kronenthaler** [comment]
would you share the way you are doing so? it might be handy to add it for other developers

**Comment by Drusy** [comment]
Actually yes, I should ! 
I have done it the quick and dirty way, just give me few time to check everything.
