### ISSUE TITLE
Cannot add files to a new folder in Xcode

### ISSUE THREAD

**Issue by Draveness** [kronenthaler/mod-pbxproj#37]
```
new_group = project.get_or_create_group('new_group')
group = project.get_or_create_group('classes')
new_group.add_child(group)

project.add_file('file.m', group)
project.save()
```

These code doesn't create a subfolder in `new_group` folder, it just create a folder in the root of a project... How can I make the `classes` group under the `new_group` folder

**Comment by kronenthaler** [comment]
Please, checkout the full signature of get_or_create group: 
```
def get_or_create_group(self, name, path=None, parent=None):
```
you can achieve what you want with:
```
new_group = project.get_or_create_group('new_group')
group = project.get_or_create_group('classes', None, new_group)
```

**Comment by Draveness** [comment]
Fix it, thx so much, I have focused on this problem for three days.
