### ISSUE TITLE
Import Error: cannot import name XcodeProject

### ISSUE THREAD

**Issue by surrealarboreal** [kronenthaler/mod-pbxproj#45]
Hey. I cannot for the life of me figure out why XcodeProject will not import. the class is defined and mod_pbxproj is installed. Any ideas?

**Comment by kronenthaler** [comment]
any stack trace or something to work with?

**Comment by surrealarboreal** [comment]
source:

#!/usr/bin/python

import sys
from mod_pbxproj import XcodeProject

pathToProjectFile = sys.argv[1] + '/Unity-iPhone.xcodeproj/project.pbxproj'
pathToNativeCodeFiles = sys.argv[2]

project = XcodeProject.Load( pathToProjectFile )

trace: 

Traceback (most recent call last):
    from mod_pbxproj import XcodeProject
ImportError: cannot import name XcodeProject

**Comment by kronenthaler** [comment]
give it a try

**Comment by surrealarboreal** [comment]
Fixed, thanks.
