### ISSUE TITLE
about flag

### ISSUE THREAD

**Issue by huazi2015** [kronenthaler/mod-pbxproj#59]
exceuse me, kronenthaler, ask your  a question.
i want ask a quesiton.
in xcode project (kronenthaler's python script). how to add some flag, like -ObjC, Preprocessor Macros, Enable C++ Exception? use which method?

please forgive my poor english, thank you a lot, kronenthaler

**Comment by huazi2015** [comment]
-ObjC, Preprocessor Macros, Enable C++ Exception. these flag

**Comment by huazi2015** [comment]
help me,

**Comment by kronenthaler** [comment]
Third strike: spamming. I'm not going to reply any faster because you want it to or you send more messages. Don't be lazy and read the file for the method you want.
You are being reported for abuse.
