### ISSUE TITLE
Is there a way to get the public/private/project header files for a target?

### ISSUE THREAD

**Issue by dnkoutso** [kronenthaler/mod-pbxproj#67]
You can close this issue, just wanted to ask this question.

**Comment by kronenthaler** [comment]
I just checked, the information is in the project, but it's something needs to be filtered out. Currently there is no such thing in the XcodeProject class.

I leave this issue as open and labeled as an enhancement

**Comment by dnkoutso** [comment]
I might take a stub at it.

**Comment by kronenthaler** [comment]
Take a look at: PBXBuildFile section and look up for the settings property and the key ATTRIBUTES within it.
