### ISSUE TITLE
Not support python3

### ISSUE THREAD

**Issue by alexazhou** [kronenthaler/mod-pbxproj#68]
when use python3, it say that:

>>> from mod_pbxproj import XcodeProject
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'mod_pbxproj'

Great and useful project, but support python3 will be better

**Comment by kronenthaler** [comment]
The script is for python 2.x until the default installation on mac becomes
python3. I intentionally dropped support for python 3 because the versions
were diverging too much and was unmaintainable.

**Comment by hackalog** [comment]
FWIW, It now appears that python3 is supported?

**Comment by evanxlh** [comment]
I use this library in macos 11 with Xcode 13.2, also encountered this issue: ImportError: No module named pbxproj

@kronenthaler Could you please give me some suggestions?
