### ISSUE TITLE
Adding framework example in readme is reporting error

### ISSUE THREAD

**Issue by luxel** [kronenthaler/mod-pbxproj#69]
In the readme, when using below line:

project.add_file_if_doesnt_exist('System/Library/Frameworks/AdSupport.framework', parent=frameworks, weak=True, tree='SDKROOT')

We'll receive error that "NameError: global name 'frameworks' is not defined".

Changed the line into:

project.add_file_if_doesnt_exist('System/Library/Frameworks/AdSupport.framework', parent='frameworks', weak=True, tree='SDKROOT')

And it worked. 8-)

**Comment by kronenthaler** [comment]
parent could be a group object or string. The example is set to use the object to show that the framework can be added to any group that has been created, for instance: Libraries/3rdParty/frameworks instead of dropping everything in the top level.
