### ISSUE TITLE
Specify where you want the settings applied: targets or project

### ISSUE THREAD

**Issue by mulle-nat** [kronenthaler/mod-pbxproj#72]
Currently when you run the commandline tool with `-af` it changes the settings in all targets **and** in the project. This is extremely redundant. 

When you specify f.i. **HEADER_SEARCH_PATHS** as `\$(inherited):/usr/local/include`, Xcode will eventually expand it into  `/usr/local/include /usr/local/include`. 

That becomes extremely tedious, when you have multiple search paths.

**Comment by mulle-nat** [comment]
Eventually, because I needed this, I wrote my own tool [mulle-xcode-settings](http://www.mulle-kybernetik.com/software/git/mulle-xcode-settings/about) to do that.

**Comment by kronenthaler** [comment]
Included on 2.0.0 version
