### ISSUE TITLE
The header phase is destroyed when modifying a Project

### ISSUE THREAD

**Issue by mulle-nat** [kronenthaler/mod-pbxproj#73]
Well it's curious, that this never popped up, but I guess most people don't write libraries.

``` console
$ grep PBXHeadersBuildPhase A.xcodeproj/project.pbxproj
/* Begin PBXHeadersBuildPhase section */
            isa = PBXHeadersBuildPhase;
/* End PBXHeadersBuildPhase section */
$ python -m mod_pbxproj -b -af "FOO=1" A.xcodeproj All
$ grep PBXHeadersBuildPhase A.xcodeproj/project.pbxproj
$
```

That's pretty bad.

**Comment by jonnyijapan** [comment]
I think you are supposed to specify the path to the project.pbxproj inside the xcodeproj? At least I do.

**Comment by mulle-nat** [comment]
That (obviously BTW) made no difference.

**Comment by kronenthaler** [comment]
This issue has been resolved in the new cli
