### ISSUE TITLE
Disable bit code of project?

### ISSUE THREAD

**Issue by jonnyijapan** [kronenthaler/mod-pbxproj#74]
Is it possible to disable bit code of project with this thing?

I think I have a version of this from ~6 months ago. Should I update to a newer version for Xcode 7?

**Comment by jonnyijapan** [comment]
Got it! From CLI, something like this

```
python -m mod_pbxproj -b -af ENABLE_BITCODE=NO Unity-iPhone.xcodeproj/project.pbxproj All
```

Thanks!

**Comment by jonnyijapan** [comment]
Ok, I don't know how to do that from a python script. Tried this:

```
project = XcodeProject.Load(pathProjectfile)
project.add_flags('ENABLE_BITCODE', False)
```

I get the feeling "all" is missing?!

**Comment by jonnyijapan** [comment]
I got it! Maybe you should update the readme because the instructions didn't work! I peeked at the source and got this:

```
project = XcodeProject.Load(pathProjectfile)
project.add_flags({'ENABLE_BITCODE':'NO'})
```


Thanks again.

**Comment by kronenthaler** [comment]
I will close it until more context it's given why it's still open.
