### ISSUE TITLE
is there any way can add a framework file as 'PBXSourcesBuildPhase' not 'PBXFrameworksBuildPhase'

### ISSUE THREAD

**Issue by showhilllee** [kronenthaler/mod-pbxproj#83]
We try to load swift framework in OC project,We found that the framework add as 'PBXSourcesBuildPhase' type can be load success.So I want to know is there any way can add a framework file as 'PBXSourcesBuildPhase'?

**Comment by kronenthaler** [comment]
Short answer, no. Long answer, frameworks are a special kind of file for xcode and have to be added under the frameworks build phase because they have a special meaning and treatment from xcode, not adding them on the correct build phase will make the project to fail on linking time.
