### ISSUE TITLE
PBXLegacyTarget not supported

### ISSUE THREAD

**Issue by jimon** [kronenthaler/mod-pbxproj#86]
I'm getting ```warning: unknown PBX type: PBXLegacyTarget``` when trying to open a project with external build system target :(

**Comment by kronenthaler** [comment]
Could i have a sample of the PBXLegacyTarget structure of the project?

**Comment by jimon** [comment]
Sure, here : https://gist.github.com/jimon/cfa4e384012d0014c6e2#file-project-pbxproj-L37-L52
Though I just created a new external build system project, so not sure if it contains all fields?

**Comment by kronenthaler** [comment]
I have created a branch https://github.com/kronenthaler/mod-pbxproj/tree/issue-86 with a potential fix.
Please give it a go, and let me know if it works as expected.

**Comment by jimon** [comment]
Looks ok to me :+1:

**Comment by kronenthaler** [comment]
Resolved in PR #88
