### ISSUE TITLE
Remove target from XCode Project

### ISSUE THREAD

**Issue by liszto** [kronenthaler/mod-pbxproj#89]
Hi kronenthaler,
This is more a question than a request.
Is there any way to remove a target from the xcode project ?
Or need I to develop some thing in PBXNativeTarget, PBXVariantGroup, PBXContainerItemProxy, PBXTargetDependency, ...
cause a target is referenced in all those sections.

**Comment by kronenthaler** [comment]
I took a quick look. It seems there is nothing to create or remove targets. I assumed the project will be already created with targets and i could do is modify them.
That being said, what you need to do is something similar to what it's done in the methods: `get_build_phases` and `get_target_by_name`.
Iterate over the elements until you find the target name you want to delete and then remove from the self.objects reference. Maybe some extra stuff needs to be deleted somewhere else.
If you manage to implement it feel free to open a PR i will check it and merge it after some testing

**Comment by liszto** [comment]
Yes that's it !
My issue is just when Unity create a xcodeproj from scratch. He creates a target "Tests" and I would remove it.
So I will do what you said when I have enough time to do it. Cause I think there is more thing than just delete some references.

I'll keep you in touch if I made some progress during the upcoming week. And maybe if I have some deep question on the code in mod_pbxproj (but it must be fine to understand)

**Comment by jakemumu** [comment]
I know this is ancient but was there ever a neat solution for this? 

I've tried: 

```
for target in targets:
  if target.name in ['install', 'ZERO_CHECK']:
    targets.remove(target)
    or 
    del target
```

to no success
