### ISSUE TITLE
After processing, get error xcconfig file not found

### ISSUE THREAD

**Issue by garvankeeley** [kronenthaler/mod-pbxproj#91]
Just started happening recently (Xcode 7.3 maybe?).
My project has a single xcconfig file, and after processing with mod-pbxproj to add files, Xcode fails to build as it claims the xcconfig "path couldn't be resolved, it may be missing."
Prior to processing with mod-pxproj, the build does not complain about a missing xcconfig.

I found that after I open the project if I trigger the project to resave, then quit and restart Xcode, I no longer get the error.

For now, anyone know a way to get Xcode to open a project and re-save it, without doing this manually? To trigger the save, one has to make a project modification, it isn't enough to simply open and close the project in Xcode. 

Unrelated:
Skimming the code in regards to xcconfig, I notice this line is incorrect (although would have no effect as it is in comment section):
https://github.com/kronenthaler/mod-pbxproj/blame/master/mod_pbxproj/mod_pbxproj.py#L1304
The string
`'Build configuration list for PBXProject "Unity-iPhone"'`
should have correct file name, not Unity-iPhone

Still investigating, but reporting in case someone can direct me to an answer.

**Comment by kronenthaler** [comment]
Thanks for the report.
Maybe checking the build configuration section after it's modified by mod-pbxproj and after you resave it with Xcode. It might point to what is being missed.
Regarding the comment, it was hardcoded to unity-iphone as this project started for unity builds that depend on the position of specific comments like that. It could be improved, but as it's a comment has no effect on a normal Xcode project as they will be regenerated after it's save from Xcode.
