### ISSUE TITLE
I ask for help about adding the embed frameworks.

### ISSUE THREAD

**Issue by Daford** [kronenthaler/mod-pbxproj#92]
hi kronenthaler，

- Recently, I have been concerned about updating the mod-pbxproj。Today I saw the branch of the 2.0.0 version and learned about it, it seems that did not solve my problem.

- The following code blocks from an project.pbxproj：

`96F0E2B21CC8BBEC00C2DD4A /* xsdkFramework.framework in Embed Frameworks */ = {isa = PBXBuildFile; fileRef = 96F0E2AC1CC8BBE100C2DD4A /* xsdkFramework.framework */; settings = {ATTRIBUTES = (CodeSignOnCopy, RemoveHeadersOnCopy, ); }; };`

`/* Begin PBXCopyFilesBuildPhase section */

		96AABB4B1CC871BB000DF362 /* Embed Frameworks */ = {
			isa = PBXCopyFilesBuildPhase;
			buildActionMask = 2147483647;
			dstPath = "";
			dstSubfolderSpec = 10;
			files = (
				96F0E2B21CC8BBEC00C2DD4A /* xsdkFramework.framework in Embed Frameworks */,
			);
			name = "Embed Frameworks";
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXCopyFilesBuildPhase section */`

`963754661B413BF500F67766 /* XsdkIMP */ = {

			isa = PBXNativeTarget;
			buildConfigurationList = 963754731B413BF500F67766 /* Build configuration list for PBXNativeTarget "XsdkIMP" */;
			buildPhases = (
				963754671B413BF500F67766 /* Sources */,
				9637546C1B413BF500F67766 /* Frameworks */,
				9637546E1B413BF500F67766 /* Resources */,
				96AABB4B1CC871BB000DF362 /* Embed Frameworks */,
			);
			buildRules = (
			);
			dependencies = (
			);
			name = "XsdkIMP";
			productName = XsdkIMP;
			productReference = 963754761B413BF500F67766 /* XsdkIMP.app */;
			productType = "com.apple.product-type.application";
		};`

- I tried to modify the source code, but failed.I knew it's easy for you to change this. Can you help or guide me to add the embed frameworks?
- Thank you very much!

**Comment by kronenthaler** [comment]
Branch 2.0.0 it's a work in progress, currently it doesn't do anything useful.
The embed-frameworks are not supported out of the box by the project yet. It has been marked as an improvement, but the refactor for the new version has to happen first to allow easier changes.
